spring:
  application:
    name: driveindex
  main:
    allow-bean-definition-overriding: true
  web:
    resources:
      add-mappings: false
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.MariaDBDialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    locations: classpath:/flyway